version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=your_stripe_public_key
      - STRIPE_SECRET_KEY=your_stripe_secret_key
    depends_on:
      - prisma
  prisma:
    image: prismagraphql/prisma:latest
    restart: always
    environment:
      PRISMA_DATABASE_URL: "postgresql://user:password@prisma-db:5432/dev"
    ports:
      - "5555:5555"
